# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-17 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_products', '0003_auto_20180117_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='featurespecial',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price base'),
        ),
        migrations.AlterField(
            model_name='productfinal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='productfinal',
            name='price_base',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Price base'),
        ),
        migrations.AlterField(
            model_name='productfinal',
            name='price_base_local',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If it is empty, price base is equal to price base of product', max_digits=10, null=True, verbose_name='Price base'),
        ),
    ]
