# Generated by Django 4.0.4 on 2022-05-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_products', '0012_productunique_caducity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='public',
            field=models.BooleanField(blank=True, default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='outstanding',
            field=models.BooleanField(blank=True, default=True, verbose_name='Outstanding'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='show_menu',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show menu'),
        ),
        migrations.AlterField(
            model_name='brandtexten',
            name='public',
            field=models.BooleanField(blank=True, default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='brandtextes',
            name='public',
            field=models.BooleanField(blank=True, default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='category',
            name='public',
            field=models.BooleanField(blank=True, default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_menu',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show menu'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_only_product_stock',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show only products in stock'),
        ),
        migrations.AlterField(
            model_name='family',
            name='public',
            field=models.BooleanField(blank=True, default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='family',
            name='show_menu',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show menu'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='public',
            field=models.BooleanField(blank=True, default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='featurespecial',
            name='public',
            field=models.BooleanField(blank=True, default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='featurespecial',
            name='unique',
            field=models.BooleanField(blank=True, default=True, verbose_name='The value must unique'),
        ),
        migrations.AlterField(
            model_name='flagshipproduct',
            name='public',
            field=models.BooleanField(blank=True, default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='flagshipproduct',
            name='view_video',
            field=models.BooleanField(blank=True, default=False, verbose_name='View video'),
        ),
        migrations.AlterField(
            model_name='product',
            name='caducable',
            field=models.BooleanField(blank=True, default=False, verbose_name='Caducable'),
        ),
        migrations.AlterField(
            model_name='product',
            name='force_stock',
            field=models.BooleanField(blank=True, default=True, verbose_name='Force stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='of_purchase',
            field=models.BooleanField(blank=True, default=True, verbose_name='Purchase'),
        ),
        migrations.AlterField(
            model_name='product',
            name='of_sales',
            field=models.BooleanField(blank=True, default=True, verbose_name='Sales'),
        ),
        migrations.AlterField(
            model_name='product',
            name='public',
            field=models.BooleanField(blank=True, default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='productfinal',
            name='most_sold',
            field=models.BooleanField(blank=True, default=False, verbose_name='Most sold'),
        ),
        migrations.AlterField(
            model_name='productfinal',
            name='offer',
            field=models.BooleanField(blank=True, default=False, verbose_name='Offer'),
        ),
        migrations.AlterField(
            model_name='productfinal',
            name='outstanding',
            field=models.BooleanField(blank=True, default=False, verbose_name='Outstanding'),
        ),
        migrations.AlterField(
            model_name='productfinal',
            name='sample',
            field=models.BooleanField(blank=True, default=False, help_text='If this option is checked the product can not be sold', verbose_name='Sample'),
        ),
        migrations.AlterField(
            model_name='productfinalimage',
            name='public',
            field=models.BooleanField(blank=True, default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='productfinaltexten',
            name='public',
            field=models.BooleanField(blank=True, default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='productfinaltextes',
            name='public',
            field=models.BooleanField(blank=True, default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='public',
            field=models.BooleanField(blank=True, default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='producttexttexten',
            name='public',
            field=models.BooleanField(blank=True, default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='producttexttextes',
            name='public',
            field=models.BooleanField(blank=True, default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='outstanding',
            field=models.BooleanField(blank=True, default=False, verbose_name='Outstanding'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='public',
            field=models.BooleanField(blank=True, default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='show_brand',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show brand (for menu)'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='show_menu',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show menu'),
        ),
    ]
