# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 10:34
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings

from codenerix_products.models import MODELS, \
    GroupValueAttribute, Attribute, OptionValueAttribute, \
    GroupValueFeature, Feature, OptionValueFeature, \
    GroupValueFeatureSpecial, FeatureSpecial, OptionValueFeatureSpecial

for info in MODELS:
    field = info[0]
    model = info[1]
    for lang_code in settings.LANGUAGES_DATABASES:
        cad = "from codenerix_products.models import {}Text{}\n".format(model, lang_code)
        exec(cad)


def migrate_group_value(model_group, model_source, model_option):
    model_str = str(model_option).replace('"', '').replace("'", '').replace(">", '').split(".")[-1]
    features = model_source.objects.all()
    for feature in features:
        if feature.list_value:
            group = model_group.objects.filter(name=feature.list_value.name).first()
            if not group:
                group = model_group()
                group.name = feature.list_value.name
                group.save()
            for option in feature.list_value.options_value.all():
                opt = model_option()
                opt.group = group
                opt.save()
                for lang_code in settings.LANGUAGES_DATABASES:
                    model_lang = globals()["{}Text{}".format(model_str, lang_code)]
                    description = getattr(option, lang_code.lower()).description
                    
                    opt_lang = model_lang.objects.filter(description=description, option_value=opt).first()
                    
                    if not opt_lang:
                        opt_lang = model_lang()
                        opt_lang.description = description
                        opt_lang.option_value = opt
                        opt_lang.save()


def run_migrate(apps, schema_editor):
    migrate_group_value(GroupValueAttribute, Attribute, OptionValueAttribute)
    migrate_group_value(GroupValueFeature, Feature, OptionValueFeature)
    migrate_group_value(GroupValueFeatureSpecial, FeatureSpecial, OptionValueFeatureSpecial)


class Migration(migrations.Migration):
    dependencies = [
        ('codenerix_products', '0013_optionvalueattributetexten_optionvalueattributetextes_optionvaluefeaturespecialtexten_optionvaluefea'),
    ]

    operations = [
        migrations.RunPython(run_migrate),
    ]
