# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_products', '0025_auto_20170802_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='packoption',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Order'),
        ),
    ]
