# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-18 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_products', '0036_auto_20171017_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='productfinal',
            name='code',
            field=models.CharField(blank=True, help_text='If it is empty, code is equal to code product', max_length=250, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='productfinal',
            name='price_base_local',
            field=models.FloatField(blank=True, help_text='If it is empty, price base is equal to price base of product', null=True, verbose_name='Price base'),
        ),
    ]
