# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-12 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_products', '0042_auto_20171110_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfinaltexten',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='TAGs'),
        ),
        migrations.AddField(
            model_name='productfinaltextes',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='TAGs'),
        ),
        migrations.AddField(
            model_name='producttexttexten',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='TAGs'),
        ),
        migrations.AddField(
            model_name='producttexttextes',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='TAGs'),
        ),
    ]
