# Generated by Django 2.0 on 2018-01-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_storages', '0003_auto_20180110_1536'),
        ('codenerix_products', '0042_auto_20171110_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunique',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_unique', to='codenerix_storages.StorageBox', verbose_name='Box'),
        ),
    ]
