# Generated by Django 2.0.6 on 2018-09-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_products', '0043_auto_20180112_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='url_external',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Url external'),
        ),
    ]
